### ISSUE TITLE
请问下面这段话怎么理解？具体应用的行为是怎样？

### ISSUE THREAD

**Issue by dustturtle** [HustHank/BackgroundDownloadDemo#1]
“添加到后台会话的任务在外部进程运行，即使应用程序被挂起，崩溃，或者被杀死，它依然会运行。” 应用手动kill后还可以下载吗？ 实际操作好像不可以吧？ 那这句话如何理解呢？

**Comment by HustHank** [comment]
https://developer.apple.com/reference/foundation/nsurlsessionconfiguration/1407496-backgroundsessionconfigurationwi?language=objc
以上链接是苹果的官方文档对backgroundSessionConfigurationWithIdentifier：的说明，上面说到
“Use this method to initialize a configuration object suitable for transferring data files while the app runs in the background. A session configured with this object hands control of the transfers over to the system, which handles the transfers in a separate process. In iOS, this configuration makes it possible for transfers to continue even when the app itself is suspended or terminated.

If an iOS app is terminated by the system and relaunched, the app can use the same identifier to create a new configuration object and session and retrieve the status of transfers that were in progress at the time of termination. ...”

苹果说明了， this configuration makes it possible for transfers to continue even when the app itself is suspended or terminated.

**Comment by dustturtle** [comment]
恩，这个文档我也看了。具体场景难以验证啊
