### ISSUE TITLE
请问默认配置的session如何断点下载

### ISSUE THREAD

**Issue by MoozenSoft** [HustHank/BackgroundDownloadDemo#3]
后台会话能通过identifier，为它的downloadTask找到临时文件，但是默认配置的会话只会创建新的临时文件，请问退出app后再打开app默认配置的会话如何定位上次的临时文件

**Comment by HustHank** [comment]
你说的是NSURLSessionConfiguration的defaultSessionConfiguration？不支持后台下载的配置?

**Comment by MoozenSoft** [comment]
是的，如果正在下载关闭app，再打开就会新建临时文件

**Comment by HustHank** [comment]
这个就需要使用类似于以下博客的方法来断点续传了，需要设置请求头“Range”
http://www.cnblogs.com/gchlcc/p/5459546.html

这个我也没尝试过，不好意思哈。

**Comment by MoozenSoft** [comment]
谢谢指点，我用 NSURLSessionDataTask实现了断点下载，即使关app再下载也会继续下载，而不会产生新的临时文件
