### ISSUE TITLE
程序崩溃的时候，如何保存completionHandler()？

### ISSUE THREAD

**Issue by OCer** [HustHank/BackgroundDownloadDemo#6]
我测试的时候发现了些问题，表示很不解：
1、APP在下载过程中突然崩溃了，如何去保存completionHandler()？

2、在- (void)application:(UIApplication *)application handleEventsForBackgroundURLSession:(NSString *)identifier completionHandler:(void (^)(void))completionHandler 中，好像并不需要创建参照？ 我发现没创建也是OK的，不知道和创建了有什么区别

3、如果我创建了多个NSURLSession，到后台后是不是要保存多份completionHandler()？

4、我重新进入APP的时候，创建NSURLSession就自动给我继续下载了，导致我在逻辑处理出了问题，怎么让它不自动下载？

**Comment by OCer** [comment]
@HustHank 大佬

**Comment by HustHank** [comment]
1、APP在下载过程中突然崩溃，这个时候根本不需要completionHandler()，调用completionHandler()只是在后台下载完成后，告诉app后台任务下载完了，会唤醒app执行一些事情。

2、这里不太清楚你说的创建参照是什么意思，这里是指把completionHandler保存下载，在后台下载完成后调用

3、是的，每个session的identifier会对应一个completionHandler

4、这样你自己来管理下载数据就可以了，不要使用NSURLSessionDownloadTask了，使用NSURLSessionDataTask就可以了，自己通过URLSession:dataTask:didReceiveData:获取到的data来管理


还有，你有问题的话，去博客里问吧，不要这里问了，这里是提bug的地方~~~

**Comment by OCer** [comment]
// 你必须重新建立一个后台 seesion 的参照
    // 否则 NSURLSessionDownloadDelegate 和 NSURLSessionDelegate 方法会因为
    // 没有 对 session 的 delegate 设定而不会被调用。参见上面的 backgroundURLSession
我发现好像不需要啊  一样调用代理  用的X iOS11.1

**Comment by OCer** [comment]
我发现你的demo也是，进去后就自动下载了，如果这个时候我点击下载，会同时下载2个，你有解决思路吗

**Comment by OCer** [comment]
```
NSURLSessionDownloadTask *task = nil;
    NSData *resumeData = [[self dataDic] objectForKey:identifier];
    if (resumeData)
    {
        kLog(@"断点续传");
        // 断点续传
        if ([Tools getSystemVersion] >= 10.0f) // 解决断点续传在iOS10以上的bug
        {
            task = [session downloadTaskWithCorrectResumeData:resumeData];
        }
        else
        {
            task = [session downloadTaskWithResumeData:resumeData];
        }
    }
    else
    {
        kLog(@"开启一个新的下载");
        // 启动一个下载任务
        task = [session downloadTaskWithRequest:request];
    }
    [[self taskList] addObject:task];

    // WIFI状态开始下载
    if ([[NetworkState shareNetworkState] state] == AFNetworkReachabilityStatusReachableViaWiFi)
    {
        kLog(@"WIFI状态开始下载");
        [task resume];
        [model setDownloadState:downloadStateLoading];
      }
```

本身已经在下载了，然后检测到WiFi也开启一个下载 - -

**Comment by OCer** [comment]
解决了
